---

- hosts: all
  tasks:

  - name: install update debians
    tags: always
    apt:
      only_upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Debian"

    
  - name: install update Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 


- hosts: web_servers
  tags: nginx
  tasks:
    
  - name: install nginx and php for Ubuntu servers
    apt:
      state: latest
      name:
      - nginx
      - tmux
    when: ansible_distribution == "Ubuntu"

  - name: transfer file to Ubuntu Server
    tags: nginx
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

    
- hosts: db_servers
  tags: postgresql
  tasks:

  - name: install postgresql on Debian server
    apt:
      state: latest
      name:
      - postgresql
    when: ansible_distribution == "Debian"
